# Generated by Django 4.2.5 on 2023-11-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0037_alter_historicalcontentmetadata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tag title', max_length=255)),
                ('description', models.TextField(help_text='Tag description.')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAcademy',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(help_text='Academy title', max_length=255)),
                ('short_description', models.TextField(help_text='Short description of the academy.')),
                ('long_description', models.TextField(help_text='Long description of the academy.')),
                ('image', models.URLField(help_text='URL of the image shown on academy card on the frontend.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Academy',
                'verbose_name_plural': 'historical Academies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Academy title', max_length=255)),
                ('short_description', models.TextField(help_text='Short description of the academy.')),
                ('long_description', models.TextField(help_text='Long description of the academy.')),
                ('image', models.URLField(help_text='URL of the image shown on academy card on the frontend.')),
                ('enterprise_catalogs', models.ManyToManyField(related_name='academies', to='catalog.enterprisecatalog')),
                ('tags', models.ManyToManyField(related_name='academies', to='academy.tag')),
            ],
            options={
                'verbose_name': 'Academy',
                'verbose_name_plural': 'Academies',
            },
        ),
    ]
