# Generated by Django 5.2.8 on 2025-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='long_description_en',
            field=models.TextField(help_text='Long description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='long_description_es',
            field=models.TextField(help_text='Long description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='short_description_en',
            field=models.TextField(help_text='Short description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='short_description_es',
            field=models.TextField(help_text='Short description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='title_en',
            field=models.CharField(help_text='Academy title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='title_es',
            field=models.CharField(help_text='Academy title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalacademy',
            name='long_description_en',
            field=models.TextField(help_text='Long description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='historicalacademy',
            name='long_description_es',
            field=models.TextField(help_text='Long description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='historicalacademy',
            name='short_description_en',
            field=models.TextField(help_text='Short description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='historicalacademy',
            name='short_description_es',
            field=models.TextField(help_text='Short description of the academy.', null=True),
        ),
        migrations.AddField(
            model_name='historicalacademy',
            name='title_en',
            field=models.CharField(help_text='Academy title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalacademy',
            name='title_es',
            field=models.CharField(help_text='Academy title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_en',
            field=models.TextField(help_text='Tag description.', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_es',
            field=models.TextField(help_text='Tag description.', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(help_text='Tag title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_es',
            field=models.CharField(help_text='Tag title', max_length=255, null=True),
        ),
    ]
