# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'enterprise-catalog'
  description: "A Django-based microservice for handling Enterprise catalogs, associating enterprise customers with curated courses from the full course catalog."
  annotations:
    openedx.org/arch-interest-groups: ""
    openedx.org/release: "master"
spec:
  owner: user:alexjmpb
  type: 'service'
  lifecycle: 'production'
  dependsOn:
  - edx-enterprise
