[tox]
skipsdist = true
envlist = py{312}-django{52}
requires =
    tox-uv>=1

[pycodestyle]
ignore=E501,W503
max-line-length = 120
exclude=.git,settings,migrations,enterprise_catalog/static,bower_components,enterprise_catalog/wsgi.py

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django52: test
deps =
    django52: Django>=5.2,<5.3
commands =
    {posargs:pytest}
