# Generated by Django 4.2.11 on 2024-06-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='parent_content_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='catalog.contentmetadata'),
        ),
    ]
