# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 15:53


import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CatalogQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='All Content', max_length=255)),
                ('content_filter', jsonfield.fields.JSONField(blank=True, default={}, help_text="Query parameters which will be used to filter the discovery service's search/all endpoint results, specified as a JSON object. An empty JSON object means that all available content items will be included in the catalog.", null=True)),
            ],
            options={
                'verbose_name': 'Catalog Query',
                'verbose_name_plural': 'Catalog Queries',
            },
        ),
    ]
