# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCatalog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enterprise_uuid', models.CharField(max_length=255)),
                ('content_catalog_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_catalog_queries', to='catalog.CatalogQuery')),
            ],
            options={
                'verbose_name': 'Enterprie Catalog',
                'verbose_name_plural': 'Enterprie Catalogs',
            },
        ),
    ]
