# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_enterprisecatalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprisecatalog',
            options={'verbose_name': 'Enterprise Catalog', 'verbose_name_plural': 'Enterprise Catalogs'},
        ),
    ]
