# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-18 21:03


import django.utils.timezone
import jsonfield.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogcontentkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content_key', models.CharField(help_text='The key that represents a piece of content, such as a course, course run, or program.', max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('course_run', 'Course Run'), ('course', 'Course'), ('program', 'Program')], max_length=255)),
                ('parent_content_key', models.CharField(blank=True, help_text="The key that represents this content's parent, such as a course or program.", max_length=255, null=True)),
                ('json_metadata', jsonfield.fields.JSONField(blank=True, default={}, help_text="The metadata about a particular piece content as retrieved from the discovery service's search/all endpoint results, specified as a JSON object.", null=True)),
            ],
            options={
                'verbose_name': 'Content Metadata',
                'verbose_name_plural': 'Content Metadata',
            },
        ),
        migrations.AlterField(
            model_name='catalogcontentkey',
            name='content_key',
            field=models.ForeignKey(db_column='content_key', on_delete=django.db.models.deletion.CASCADE, related_name='caalog_content_keys', to='catalog.ContentMetadata', to_field='content_key'),
        ),
        migrations.AlterField(
            model_name='catalogquery',
            name='title',
            field=models.CharField(default='All Content', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcatalogcontentkey',
            name='content_key',
            field=models.ForeignKey(blank=True, db_column='content_key', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.ContentMetadata', to_field='content_key'),
        ),
    ]
