# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-20 18:54


import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models

import enterprise_catalog.apps.catalog.constants


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0004_contentmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecatalog',
            name='enabled_course_modes',
            field=jsonfield.fields.JSONField(default=enterprise_catalog.apps.catalog.constants.json_serialized_course_modes, help_text='Ordered list of enrollment modes which can be displayed to learners for course runs in this catalog.'),
        ),
        migrations.AddField(
            model_name='enterprisecatalog',
            name='publish_audit_enrollment_urls',
            field=models.BooleanField(default=False, help_text='Specifies whether courses should be published with direct-to-audit enrollment URLs.'),
        ),
        migrations.AddField(
            model_name='enterprisecatalog',
            name='title',
            field=models.CharField(default='All Content', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalenterprisecatalog',
            name='enabled_course_modes',
            field=jsonfield.fields.JSONField(default=enterprise_catalog.apps.catalog.constants.json_serialized_course_modes, help_text='Ordered list of enrollment modes which can be displayed to learners for course runs in this catalog.'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecatalog',
            name='publish_audit_enrollment_urls',
            field=models.BooleanField(default=False, help_text='Specifies whether courses should be published with direct-to-audit enrollment URLs.'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecatalog',
            name='title',
            field=models.CharField(default='All Content', max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogcontentkey',
            name='content_key',
            field=models.ForeignKey(db_column='content_key', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_content_keys', to='catalog.ContentMetadata', to_field='content_key'),
        ),
        migrations.AlterField(
            model_name='catalogquery',
            name='title',
            field=models.CharField(default='All Content', max_length=255),
        ),
    ]
