# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-27 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_enterprisecatalog_addtl_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContentMetadata',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content_key', models.CharField(db_index=True, help_text='The key that represents a piece of content, such as a course, course run, or program.', max_length=255)),
                ('content_type', models.CharField(choices=[('course', 'Course'), ('course_run', 'Course Run'), ('program', 'Program')], max_length=255)),
                ('parent_content_key', models.CharField(blank=True, db_index=True, help_text="The key that represents this content's parent, such as a course or program.", max_length=255, null=True)),
                ('json_metadata', jsonfield.fields.JSONField(blank=True, default={}, help_text="The metadata about a particular piece content as retrieved from the discovery service's search/all endpoint results, specified as a JSON object.", null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Content Metadata',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='catalogquery',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contentmetadata',
            name='content_type',
            field=models.CharField(choices=[('course', 'Course'), ('course_run', 'Course Run'), ('program', 'Program')], max_length=255),
        ),
        migrations.AlterField(
            model_name='contentmetadata',
            name='parent_content_key',
            field=models.CharField(blank=True, db_index=True, help_text="The key that represents this content's parent, such as a course or program.", max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enterprisecatalog',
            unique_together=set([('enterprise_uuid', 'catalog_query')]),
        ),
    ]
