# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 16:14
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_catalogquery_unique_content_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogquery',
            name='content_filter',
            field=jsonfield.fields.JSONField(default=dict, help_text="Query parameters which will be used to filter the discovery service's search/all endpoint results, specified as a JSON object."),
        ),
    ]
