# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-06 16:56


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_contentmetadata_rename_courserun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecatalog',
            name='catalog_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_catalogs', to='catalog.CatalogQuery'),
        ),
    ]
