# Generated by Django 1.11.27 on 2020-01-07 20:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_enterprisecatalog_catalog_query_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogquery',
            name='title',
        ),
    ]
