# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 16:08


import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

from enterprise_catalog.apps.catalog.constants import (
    ENTERPRISE_CATALOG_ADMIN_ROLE,
)


def create_roles(apps, schema_editor):
    """
    Create the enterprise catalog roles if they do not already exist.
    """
    EnterpriseCatalogFeatureRole = apps.get_model('catalog', 'EnterpriseCatalogFeatureRole')
    EnterpriseCatalogFeatureRole.objects.update_or_create(name=ENTERPRISE_CATALOG_ADMIN_ROLE)


def delete_roles(apps, schema_editor):
    """
    Delete the enterprise catalog roles.
    """
    EnterpriseCatalogFeatureRole = apps.get_model('catalog', 'EnterpriseCatalogFeatureRole')
    EnterpriseCatalogFeatureRole.objects.filter(name=ENTERPRISE_CATALOG_ADMIN_ROLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0012_enterprisecatalog_enterpriseuuid_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCatalogFeatureRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseCatalogRoleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enterprise_id', models.UUIDField(blank=True, null=True, verbose_name='Enterprise Customer UUID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.EnterpriseCatalogFeatureRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_roles, delete_roles),
    ]
