# Generated by Django 1.11.29 on 2020-03-23 18:12


from django.db import migrations

from enterprise_catalog.apps.catalog.constants import (
    ENTERPRISE_CATALOG_LEARNER_ROLE,
)


def create_roles(apps, schema_editor):
    """
    Create the enterprise catalog roles if they do not already exist.
    """
    EnterpriseCatalogFeatureRole = apps.get_model('catalog', 'EnterpriseCatalogFeatureRole')
    EnterpriseCatalogFeatureRole.objects.update_or_create(name=ENTERPRISE_CATALOG_LEARNER_ROLE)


def delete_roles(apps, schema_editor):
    """
    Delete the enterprise catalog roles.
    """
    EnterpriseCatalogFeatureRole = apps.get_model('catalog', 'EnterpriseCatalogFeatureRole')
    EnterpriseCatalogFeatureRole.objects.filter(name=ENTERPRISE_CATALOG_LEARNER_ROLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200323_1748'),
    ]

    operations = [
        migrations.RunPython(create_roles, delete_roles),
    ]
