# Generated by Django 2.2.12 on 2020-05-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_add_enterprise_customer_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enterprisecatalog',
            unique_together=set(),
        ),
    ]
