# Generated by Django 2.2.18 on 2021-02-24 20:56

from django.db import migrations
import uuid

def generate_uuid(apps, schema_editor):
    CatalogQuery = apps.get_model('catalog', 'CatalogQuery')
    for row in CatalogQuery.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_catalogquery_add_uuid_timestamps'),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
    ]
