# Generated by Django 2.2.23 on 2021-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_command_config_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogquery',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
