# Generated by Django 3.2.8 on 2021-11-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_catalogquery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmetadata',
            name='associated_content_metadata',
            field=models.ManyToManyField(related_name='_catalog_contentmetadata_associated_content_metadata_+', to='catalog.ContentMetadata'),
        ),
        migrations.AlterField(
            model_name='contentmetadata',
            name='parent_content_key',
            field=models.CharField(blank=True, db_index=True, help_text="The key represents this content's parent. For example for course_runs content their parent course key.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontentmetadata',
            name='parent_content_key',
            field=models.CharField(blank=True, db_index=True, help_text="The key represents this content's parent. For example for course_runs content their parent course key.", max_length=255, null=True),
        ),
    ]
