# Generated by Django 3.2.8 on 2021-11-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_catalogquery_title'),
    ]

    operations = [
     migrations.SeparateDatabaseAndState(
           state_operations=[
        migrations.CreateModel(
            name='ContentMetadataToQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.catalogquery')),
                ('content_metadata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.contentmetadata')),
            ],
            options={
                'db_table': 'catalog_contentmetadata_catalog_queries',
            },
        ),
        migrations.AlterField(
            model_name='contentmetadata',
            name='catalog_queries',
            field=models.ManyToManyField(through='catalog.ContentMetadataToQueries', to='catalog.CatalogQuery'),
        ),
    ])
     ]

