# Generated by Django 3.2.8 on 2021-11-09 23:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


def backfill_many_to_many(apps, schema_editor):
    content_metadata_model = apps.get_model("catalog", "ContentMetadata")
    catalog_query_model = apps.get_model("catalog", "CatalogQuery")
    query_content_metadata_many_to_many = content_metadata_model.catalog_queries.through.objects.all()
    content_metadata_to_queries_model = apps.get_model("catalog", "ContentMetadataToQueries")
    for row in query_content_metadata_many_to_many:
        query_object = catalog_query_model.objects.filter(id=row.catalogquery_id).first()
        content_metadata_object = content_metadata_model.objects.filter(id=row.contentmetadata_id).first()
        content_metadata_to_queries_model.objects.update_or_create(
            catalog_query=query_object,
            content_metadata=content_metadata_object
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_catalogquery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMetadataToQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.catalogquery')),
                ('content_metadata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.contentmetadata')),
            ],
        ),
        migrations.RunPython(backfill_many_to_many),
    ]


