# Generated by Django 3.2.8 on 2021-11-09 23:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20211125_0559'),
    ]
    operations = [
        migrations.CreateModel(
            name='ContentMetadataToQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.catalogquery')),
                ('content_metadata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.contentmetadata')),
            ],
        ),
        migrations.RunSQL(
            """
            /* there's some funky stuff with defaults and the timestamped model */
            INSERT INTO catalog_contentmetadatatoqueries (catalog_query_id, content_metadata_id, created, modified)
            SELECT catalogquery_id, contentmetadata_id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM catalog_contentmetadata_catalog_queries;
            """,
            """
            INSERT INTO catalog_contentmetadata_catalog_queries (catalogquery_id, contentmetadata_id)
            SELECT catalog_query_id, content_metadata_id
            FROM catalog_contentmetadatatoqueries
            WHERE NOT EXISTS (SELECT catalog_query_id FROM catalog_contentmetadata_catalog_queries A2
            WHERE A2.catalogquery_id = catalog_contentmetadatatoqueries.catalog_query_id AND
            A2.contentmetadata_id = catalog_contentmetadatatoqueries.content_metadata_id AND
            catalog_contentmetadatatoqueries.deleted_at IS NULL);
            """
        )
    ]


