# Generated by Django 3.2.8 on 2021-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_contentmetadatatoqueries'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmetadata',
            name='catalog_query_mapping',
            field=models.ManyToManyField(through='catalog.ContentMetadataToQueries', to='catalog.CatalogQuery'),
        ),
    ]
