# Generated by Django 3.2.8 on 2021-12-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20211109_2347'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentmetadatatoqueries',
            constraint=models.UniqueConstraint(fields=('content_metadata_id', 'catalog_query_id', 'deleted_at'), name='unique content metadata to query'),
        ),
    ]
