# Generated by Django 3.2.15 on 2022-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20220512_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogquery',
            name='include_exec_ed_2u_courses',
            field=models.BooleanField(default=False, help_text='Specifies whether the catalog should include exec ed courses.'),
        ),
    ]
