# Generated by Django 3.2.15 on 2022-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20220804_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogquery',
            name='content_filter_hash',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='catalogquery',
            unique_together={('content_filter_hash', 'include_exec_ed_2u_courses')},
        ),
    ]
