# Generated by Django 3.2.15 on 2022-09-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20220804_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmetadata',
            name='associated_content_metadata',
            field=models.ManyToManyField(blank=True, related_name='_catalog_contentmetadata_associated_content_metadata_+', to='catalog.ContentMetadata'),
        ),
    ]
