# Generated by Django 4.2.5 on 2023-10-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20230306_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcontentmetadata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Content Metadata', 'verbose_name_plural': 'historical Content Metadata'},
        ),
        migrations.AlterModelOptions(
            name='historicalenterprisecatalog',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Enterprise Catalog', 'verbose_name_plural': 'historical Enterprise Catalogs'},
        ),
        migrations.AlterField(
            model_name='contentmetadata',
            name='associated_content_metadata',
            field=models.ManyToManyField(blank=True, to='catalog.contentmetadata'),
        ),
        migrations.AlterField(
            model_name='historicalcontentmetadata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecatalog',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
