# Generated by Django 4.2.9 on 2024-02-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_alter_historicalcontentmetadata_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogquery',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='catalogquery',
            name='content_filter_hash',
            field=models.CharField(editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='catalogquery',
            name='include_exec_ed_2u_courses',
        ),
    ]
