# Generated by Django 4.2.15 on 2024-09-26 16:28

import collections
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_alter_catalogquery_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('libraries', models.ManyToManyField(to='catalog.library')),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricted_books', to='catalog.library')),
                ('parent_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_books', to='catalog.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='libraries',
            field=models.ManyToManyField(to='catalog.library'),
        ),
    ]
