# Generated by Django 4.2.15 on 2024-09-26 19:02

import collections
from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_spike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, db_column='data', default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
        migrations.RenameField(
            model_name='book',
            old_name='data',
            new_name='_data',
        ),
        migrations.AlterField(
            model_name='restrictedbook',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, db_column='data', default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
        migrations.RenameField(
            model_name='restrictedbook',
            old_name='data',
            new_name='_data',
        ),
    ]
