# Generated by Django 4.2.16 on 2024-10-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_restrictedcoursemetadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmetadata',
            name='is_restricted_run',
            field=models.BooleanField(default=False, help_text='If true, cause this run to be included in various v2 endpoints.'),
        ),
    ]
