# Generated by Django 4.2.16 on 2024-10-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_restrictedcoursemetadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrestrictedcoursemetadata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Restricted Course Metadata', 'verbose_name_plural': 'historical Restricted Course Metadata'},
        ),
        migrations.AlterModelOptions(
            name='restrictedcoursemetadata',
            options={'verbose_name': 'Restricted Course Metadata', 'verbose_name_plural': 'Restricted Course Metadata'},
        ),
    ]
