# Generated by Django 4.2.16 on 2024-10-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_contentmetadata_is_restricted_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictedcoursemetadata',
            name='unrestricted_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_courses', to='catalog.contentmetadata'),
        ),
    ]
