# Generated by Django 4.2.16 on 2024-10-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_alter_restrictedcoursemetadata_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictedcoursemetadata',
            name='restricted_run_allowed_for_restricted_course',
            field=models.ManyToManyField(through='catalog.RestrictedRunAllowedForRestrictedCourse', to='catalog.contentmetadata'),
        ),
        migrations.AlterField(
            model_name='restrictedrunallowedforrestrictedcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.restrictedcoursemetadata'),
        ),
    ]
