# Generated by Django 5.2.8 on 2025-12-05 02:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictedcoursemetadata',
            name='restricted_run_allowed_for_restricted_course',
            field=models.ManyToManyField(through='catalog.RestrictedRunAllowedForRestrictedCourse', through_fields=('course', 'run'), to='catalog.contentmetadata'),
        ),
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('language_code', models.CharField(help_text="ISO 639-1 language code (e.g., 'es' for Spanish)", max_length=10)),
                ('title', models.CharField(blank=True, help_text='Translated title', max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, help_text='Translated short description', null=True)),
                ('full_description', models.TextField(blank=True, help_text='Translated full description', null=True)),
                ('outcome', models.TextField(blank=True, help_text='Translated learning outcomes', null=True)),
                ('prerequisites', models.TextField(blank=True, help_text='Translated prerequisites', null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Translated subtitle', max_length=255, null=True)),
                ('source_hash', models.CharField(help_text='SHA256 hash of source content to detect changes', max_length=64)),
                ('content_metadata', models.ForeignKey(help_text='The content metadata this translation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.contentmetadata')),
            ],
            options={
                'verbose_name': 'Content Translation',
                'verbose_name_plural': 'Content Translations',
                'indexes': [models.Index(fields=['content_metadata', 'language_code'], name='catalog_con_content_bb6ff8_idx')],
                'unique_together': {('content_metadata', 'language_code')},
            },
        ),
    ]
