# Generated by Django 3.2.16 on 2023-01-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecurationconfig',
            name='can_only_view_highlight_sets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalenterprisecurationconfig',
            name='can_only_view_highlight_sets',
            field=models.BooleanField(default=False),
        ),
    ]
