# Generated by Django 4.2.23 on 2025-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_alter_historicalenterprisecurationconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedcontent',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highlightedcontent',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order for favorited items, in ascending order (0=first)'),
        ),
        migrations.AddField(
            model_name='historicalhighlightedcontent',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalhighlightedcontent',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order for favorited items, in ascending order (0=first)'),
        ),
    ]
