name: Django CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        django-version: [django52]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Start container
      run: |
        docker compose -f .github/docker-compose-github.yml up -d
    - name: Install test dependencies and run validation
      run: |
        docker exec -e TOXENV=py312-${{ matrix.django-version }} -u root edx.devstack.enterprise-catalog /edx/app/enterprise_catalog/enterprise_catalog/validate.sh
    - name: Code Coverage
      if: matrix.python-version == '3.12' && matrix.django-version=='django52'
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
